[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "discopyright"
version = "0.1.0"
description = "Core functionality for the movie guessing task using various LLM models."
readme = "README.md"
requires-python = ">=3.8"
license = { file = "LICENSE" }
authors = [
    { name = "Andre V. Duarte", email = "andre.v.duarte@tecnico.ulisboa.pt" }
]

# Base dependencies (needed for any usage of your package)
dependencies = [
    "pandas==2.2.3",        # Matching installed version
    "Pillow==10.4.0",       # Matching installed version
    "tqdm==4.66.5",         # Matching installed version
    "pydantic==2.9.2",      # Matching installed version
    "datasets==3.0.1"       # Matching installed version
]

[project.optional-dependencies]
# Optional extras for different model branches:

# Gemini branch: uses Google's generative AI client.
gemini = [
    "google-genai==1.0.0"
]

# GPT branch: uses OpenAI's client.
gpt = [
    "openai==1.47.1"
]

# Qwen branch: requires Transformers, Torch, and qwen-vl-utils.
qwen = [
    "transformers==4.46.1",
    "torch==2.4.0",               # CUDA Version 11.6
    "qwen-vl-utils==0.0.8"
]

# Llama branch: requires Transformers, Torch, and Hugging Face Hub.
llama = [
    "transformers==4.46.1",
    "torch==2.4.0",               # CUDA Version 11.6
    "huggingface-hub==0.25.1"
]

# An extra that combines all optional dependencies.
all = [
    "google-genai==1.0.0",
    "openai==1.47.1",
    "transformers==4.46.1",
    "torch==2.4.0",               # CUDA Version 11.6
    "qwen-vl-utils==0.0.8",
    "huggingface-hub==0.25.1"
]
